platform:
  data_parquet_dir: /pscratch/sd/t/tihsu/database/ZtautauAnalysis/ml_baseline_full_analysis/evenet-input/train-diffusion
  data_parquet_val_dir: /pscratch/sd/t/tihsu/database/ZtautauAnalysis/ml_baseline_full_analysis/evenet-input/val-diffusion
  number_of_workers: 16
  resources_per_worker: {
    "CPU": 20,
    "GPU": 1,
  }
  batch_size: 2048
  prefetch_batches: 1
  use_gpu: true

logger:
  wandb:
    project: "EveNet"
    run_name: &logger_name "LEP-TauNu-Pretrain"
    tags: ["EveNet", "LEP"]
    entity: ytchou97-university-of-washington
    simplified: false
  local:
    save_dir: /tmp/tihsu/logs
    name: *logger_name
    version: "v1"

options:
  default: ../EveNet-Full/share/options/options.yaml
  Training:
    total_epochs: 1500
    epochs: 1500
    model_checkpoint_save_path: /pscratch/sd/t/tihsu/database/ZtautauAnalysis/ml_baseline_full_analysis/checkpoint-pretrain-diffusion
    model_checkpoint_load_path: null
    pretrain_model_load_path: /pscratch/sd/t/tihsu/database/ZtautauAnalysis/ml_baseline/checkpoint-pretrain-diffusion/last-v4.ckpt
    freeze_modules: []
    diffusion_every_n_epochs: 20
    diffusion_every_n_steps: 1
    eval_metrics_every_n_epochs: 1
    apply_event_weight: false

    learning_rate: &lr 0.0002
    learning_rate_body: &lr_body 0.00002
    learning_rate_classification: &lr_classification 0.0002
    learning_rate_median: &lr_median 0.0002

    Components:
      InvisibleInputProjector:
        learning_rate: *lr
        optimizer_group: "projector"
        optimizer_type: "adamW"
      
      GroupedSequentialEmbedding:
        learning_rate: *lr
        optimizer_group: "projector"
        optimizer_type: "adamW"
        warm_up: true
        weight_decay: 0.01
        decoupled_weight_decay: true

      GlobalEmbedding:
        learning_rate: *lr
        optimizer_group: "body" # learning rate based on the first component
        optimizer_type: "adamW"
        warm_up: true


      PET:
        learning_rate: *lr_body
        optimizer_group: "body"
        optimizer_type: "adamW"
        warm_up: true

      ObjectEncoder:
        learning_rate: *lr_median
        optimizer_group: "object_encoder"
        optimizer_type: "adamW"
        warm_up: true


      Classification:
        learning_rate: *lr_classification
        include: false
        optimizer_type: "adamW"

      Regression:
        include: false

      Assignment:
        include: false

      Segmentation:
        include: false

      GlobalGeneration:
        include: false

      ReconGeneration:
        include: false

      TruthGeneration:
        include: true
        diffusion_steps: 50
        optimizer_type: "adamW"
        learning_rate: *lr



    EarlyStopping:
      patience: 1000
      min_delta: 0.0
      monitor: "val/loss"
      mode: "min"
      verbose: true

    FAMO:
      turn_on: false
      detailed_loss: false

    EMA:
      enable: true
      decay: 0.999
      start_epoch: 0
      update_every_n_steps: 1
      replace_model_after_load: true
      replace_model_at_end: false

    ProgressiveTraining:
      stages:
        - name: "neutrino_only"
          epoch_ratio: 1.0
          transition_ratio: 0.0
          loss_weights:
            generation-truth: [1.0, 1.0]

  Dataset:
    dataset_limit: 1.0
    normalization_file: /pscratch/sd/t/tihsu/database/ZtautauAnalysis/ml_baseline_full_analysis/evenet-input/normalization.pt
    val_split: [0.8, 1.0]

  Metrics:
    Generation-Binning:
      # EveNet-Full currently interprets this value as the number of edges,
      # so 121 here gives 120 visible bins in wandb.
      "neutrino-energy": [ 121, 0, 60 ]
      "neutrino-pt": [ 121, 0, 60 ]
      "neutrino-eta": [ 121, -0.15, 0.15]
      "neutrino-phi": [ 121, -0.05, 0.05 ]
      "neutrino-theta": [ 121, -0.05, 0.05]
    ObjectTag-Embedding:
      enable: true
      group_name: "ObjectTag"
      label_feature: "Part_pdgId"
      max_points: 10000
      max_batches: 10
      log_every_n_epochs: 20
      alpha: 0.8
      marker_size: 8.0
      outlier_percentile_low: 0.5
      outlier_percentile_high: 99.5
      others_label: "others"
      interested_labels:
        "41": "pi"
        "2": "e"
        "6": "mu"
        "21": "gamma"
        "42": "K"
        "47": "pi0"
        "61": "K_S0"
        "62": "K_L0"
        "65": "p"
        "66": "n"

network:
  default: ../EveNet-Full/share/network/network-20M.yaml

  Body:
    GroupedSequentialEmbedding:
      hidden_dim_scale: 2.0
      dropout: 0.0

    PET:
      feature_drop: 0.0

  TruthGeneration:
    feature_drop: 0.0

event_info:
  default: generated_event_info.yaml

resonance:
  default: resonance.yaml
